# Generated by Django 5.0.6 on 2024-07-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
    ]
